export const users = [
  {
    username: "admin",
    email: "admin@gmail.com",
    password: "1234",
    verifyCode: "11111111",
  },
  {
    username: "TuanAnh",
    email: "nguyentuananh-it@gmail.com",
    password: "nguyentuananh-it",
    verifyCode: "22222222",
  },
  {
    username: "KhanhHung",
    email: "KhanhHungTran@gmail.com",
    password: "KhanhHungTran",
    verifyCode: "33333333",
  },
];

export const studentInfor = [
  {
    studentName: "Trịnh Đức Thưởng",
    studentClass: "8",
    studentClassCode: "B",
    studentMhs: "THCS_2113",
    studentMsv: "MSV_001",
    studentState: "Đang học",
    studentSemester: "2021-2025",
    studentGender: "Male",
    studentDantoc: "Kinh",
    studentNs: "Bách Thuận, Vũ Thư, Thái Bình",
    studentCCCD: "034203005852",
    studentDob: "28/07/2003",
    studentEmail: "trinhthuong26022003@gmail.com",
    studentNumber: "0868472032",
    studentAddress: "Định Công, Hoàng Mai, Hà Nội",
    studentResident: "Bách Thuận, Vũ Thư, Thái Bình",
  },
  {
    studentName: "Nguyễn Văn An",
    studentClass: "9",
    studentClassCode: "A",
    studentMhs: "THCS_2114",
    studentMsv: "MSV_002",
    studentState: "Đang học",
    studentSemester: "2021-2025",
    studentGender: "Male",
    studentDantoc: "Kinh",
    studentNs: "Hà Nội",
    studentCCCD: "034203005853",
    studentDob: "15/05/2004",
    studentEmail: "nguyenvanan@gmail.com",
    studentNumber: "0912345678",
    studentAddress: "Cầu Giấy, Hà Nội",
    studentResident: "Hà Nội",
  },
  {
    studentName: "Lê Thị Bình",
    studentClass: "10",
    studentClassCode: "C",
    studentMhs: "THCS_2115",
    studentMsv: "MSV_003",
    studentState: "Đang học",
    studentSemester: "2021-2025",
    studentGender: "Female",
    studentDantoc: "Kinh",
    studentNs: "Hải Phòng",
    studentCCCD: "034203005854",
    studentDob: "20/10/2005",
    studentEmail: "lethibinh@gmail.com",
    studentNumber: "0987654321",
    studentAddress: "Lê Chân, Hải Phòng",
    studentResident: "Hải Phòng",
  },
  {
    studentName: "Phạm Minh Hoàng",
    studentClass: "11",
    studentClassCode: "D",
    studentMhs: "THCS_2116",
    studentMsv: "MSV_004",
    studentState: "Đang học",
    studentSemester: "2021-2025",
    studentGender: "Male",
    studentDantoc: "Kinh",
    studentNs: "Đà Nẵng",
    studentCCCD: "034203005855",
    studentDob: "12/12/2004",
    studentEmail: "phamminhhoang@gmail.com",
    studentNumber: "0901234567",
    studentAddress: "Hải Châu, Đà Nẵng",
    studentResident: "Đà Nẵng",
  },
  {
    studentName: "Trần Thị Hồng",
    studentClass: "12",
    studentClassCode: "E",
    studentMhs: "THCS_2117",
    studentMsv: "MSV_005",
    studentState: "Đang học",
    studentSemester: "2021-2025",
    studentGender: "Female",
    studentDantoc: "Kinh",
    studentNs: "Huế",
    studentCCCD: "034203005856",
    studentDob: "05/05/2003",
    studentEmail: "tranthihong@gmail.com",
    studentNumber: "0934567890",
    studentAddress: "Phú Nhuận, Huế",
    studentResident: "Huế",
  },
  {
    studentName: "Ngô Văn Cường",
    studentClass: "8",
    studentClassCode: "F",
    studentMhs: "THCS_2118",
    studentMsv: "MSV_006",
    studentState: "Đang học",
    studentSemester: "2021-2025",
    studentGender: "Male",
    studentDantoc: "Kinh",
    studentNs: "Hà Nội",
    studentCCCD: "034203005857",
    studentDob: "10/10/2005",
    studentEmail: "ngovancuong@gmail.com",
    studentNumber: "0981234567",
    studentAddress: "Hoàn Kiếm, Hà Nội",
    studentResident: "Hà Nội",
  },
  {
    studentName: "Đỗ Thị Lan",
    studentClass: "9",
    studentClassCode: "G",
    studentMhs: "THCS_2119",
    studentMsv: "MSV_007",
    studentState: "Đang học",
    studentSemester: "2021-2025",
    studentGender: "Female",
    studentDantoc: "Kinh",
    studentNs: "Hải Dương",
    studentCCCD: "034203005858",
    studentDob: "22/02/2004",
    studentEmail: "dothilan@gmail.com",
    studentNumber: "0976543210",
    studentAddress: "Nam Sách, Hải Dương",
    studentResident: "Hải Dương",
  },
  {
    studentName: "Vũ Văn Nam",
    studentClass: "10",
    studentClassCode: "H",
    studentMhs: "THCS_2120",
    studentMsv: "MSV_008",
    studentState: "Đang học",
    studentSemester: "2021-2025",
    studentGender: "Male",
    studentDantoc: "Kinh",
    studentNs: "Quảng Ninh",
    studentCCCD: "034203005859",
    studentDob: "30/03/2003",
    studentEmail: "vuvannam@gmail.com",
    studentNumber: "0967890123",
    studentAddress: "Hạ Long, Quảng Ninh",
    studentResident: "Quảng Ninh",
  },
  {
    studentName: "Lý Thị Hoa",
    studentClass: "11",
    studentClassCode: "I",
    studentMhs: "THCS_2121",
    studentMsv: "MSV_009",
    studentState: "Đang học",
    studentSemester: "2021-2025",
    studentGender: "Female",
    studentDantoc: "Kinh",
    studentNs: "Bắc Ninh",
    studentCCCD: "034203005860",
    studentDob: "18/08/2004",
    studentEmail: "lythihoa@gmail.com",
    studentNumber: "0954321098",
    studentAddress: "Từ Sơn, Bắc Ninh",
    studentResident: "Bắc Ninh",
  },
  {
    studentName: "Trương Văn Bình",
    studentClass: "12",
    studentClassCode: "J",
    studentMhs: "THCS_2122",
    studentMsv: "MSV_010",
    studentState: "Đang học",
    studentSemester: "2021-2025",
    studentGender: "Male",
    studentDantoc: "Kinh",
    studentNs: "Hà Nam",
    studentCCCD: "034203005861",
    studentDob: "25/12/2003",
    studentEmail: "truongvanbinh@gmail.com",
    studentNumber: "0943210987",
    studentAddress: "Phủ Lý, Hà Nam",
    studentResident: "Hà Nam",
  },
  {
    studentName: "Phan Thị Ngọc",
    studentClass: "8",
    studentClassCode: "K",
    studentMhs: "THCS_2123",
    studentMsv: "MSV_011",
    studentState: "Đang học",
    studentSemester: "2021-2025",
    studentGender: "Female",
    studentDantoc: "Kinh",
    studentNs: "Ninh Bình",
    studentCCCD: "034203005862",
    studentDob: "14/04/2005",
    studentEmail: "phanthingoc@gmail.com",
    studentNumber: "0932109876",
    studentAddress: "Ninh Bình",
    studentResident: "Ninh Bình",
  },
  {
    studentName: "Hoàng Văn Phúc",
    studentClass: "9",
    studentClassCode: "L",
    studentMhs: "THCS_2124",
    studentMsv: "MSV_012",
    studentState: "Đang học",
    studentSemester: "2021-2025",
    studentGender: "Male",
    studentDantoc: "Kinh",
    studentNs: "Thanh Hóa",
    studentCCCD: "034203005863",
    studentDob: "07/07/2004",
    studentEmail: "hoangvanphuc@gmail.com",
    studentNumber: "0921098765",
    studentAddress: "Thanh Hóa",
    studentResident: "Thanh Hóa",
  },
  {
    studentName: "Nguyễn Thị Hạnh",
    studentClass: "10",
    studentClassCode: "M",
    studentMhs: "THCS_2125",
    studentMsv: "MSV_013",
    studentState: "Đang học",
    studentSemester: "2021-2025",
    studentGender: "Female",
    studentDantoc: "Kinh",
    studentNs: "Nghệ An",
    studentCCCD: "034203005864",
    studentDob: "01/01/2003",
    studentEmail: "nguyenthihanh@gmail.com",
    studentNumber: "0910987654",
    studentAddress: "Vinh, Nghệ An",
    studentResident: "Nghệ An",
  },
  {
    studentName: "Trần Văn Tùng",
    studentClass: "11",
    studentClassCode: "N",
    studentMhs: "THCS_2126",
    studentMsv: "MSV_014",
    studentState: "Đang học",
    studentSemester: "2021-2025",
    studentGender: "Male",
    studentDantoc: "Kinh",
    studentNs: "Hà Tĩnh",
    studentCCCD: "034203005865",
    studentDob: "11/11/2004",
    studentEmail: "tranvantung@gmail.com",
    studentNumber: "0909876543",
    studentAddress: "Hà Tĩnh",
    studentResident: "Hà Tĩnh",
  },
  {
    studentName: "Lê Thị Mai",
    studentClass: "12",
    studentClassCode: "O",
    studentMhs: "THCS_2127",
    studentMsv: "MSV_015",
    studentState: "Đang học",
    studentSemester: "2021-2025",
    studentGender: "Female",
    studentDantoc: "Kinh",
    studentNs: "Quảng Bình",
    studentCCCD: "034203005866",
    studentDob: "09/09/2003",
    studentEmail: "lethimai@gmail.com",
    studentNumber: "0898765432",
    studentAddress: "Đồng Hới, Quảng Bình",
    studentResident: "Quảng Bình",
  },
  {
    studentName: "Phạm Văn Hùng",
    studentClass: "8",
    studentClassCode: "P",
    studentMhs: "THCS_2128",
    studentMsv: "MSV_016",
    studentState: "Đang học",
    studentSemester: "2021-2025",
    studentGender: "Male",
    studentDantoc: "Kinh",
    studentNs: "Quảng Trị",
    studentCCCD: "034203005867",
    studentDob: "06/06/2005",
    studentEmail: "phamvanhung@gmail.com",
    studentNumber: "0887654321",
    studentAddress: "Đông Hà, Quảng Trị",
    studentResident: "Quảng Trị",
  },
  {
    studentName: "Nguyễn Thị Thu",
    studentClass: "9",
    studentClassCode: "Q",
    studentMhs: "THCS_2129",
    studentMsv: "MSV_017",
    studentState: "Đang học",
    studentSemester: "2021-2025",
    studentGender: "Female",
    studentDantoc: "Kinh",
    studentNs: "Thừa Thiên Huế",
    studentCCCD: "034203005868",
    studentDob: "03/03/2004",
    studentEmail: "nguyenthithu@gmail.com",
    studentNumber: "0876543210",
    studentAddress: "Huế",
    studentResident: "Thừa Thiên Huế",
  },
  {
    studentName: "Trần Văn Long",
    studentClass: "10",
    studentClassCode: "R",
    studentMhs: "THCS_2130",
    studentMsv: "MSV_018",
    studentState: "Đang học",
    studentSemester: "2021-2025",
    studentGender: "Male",
    studentDantoc: "Kinh",
    studentNs: "Quảng Nam",
    studentCCCD: "034203005869",
    studentDob: "02/02/2003",
    studentEmail: "tranvanlong@gmail.com",
    studentNumber: "0865432109",
    studentAddress: "Tam Kỳ, Quảng Nam",
    studentResident: "Quảng Nam",
  },
  {
    studentName: "Lê Thị Hương",
    studentClass: "11",
    studentClassCode: "S",
    studentMhs: "THCS_2131",
    studentMsv: "MSV_019",
    studentState: "Đang học",
    studentSemester: "2021-2025",
    studentGender: "Female",
    studentDantoc: "Kinh",
    studentNs: "Quảng Ngãi",
    studentCCCD: "034203005870",
    studentDob: "08/08/2004",
    studentEmail: "lethihuong@gmail.com",
    studentNumber: "0854321098",
    studentAddress: "Quảng Ngãi",
    studentResident: "Quảng Ngãi",
  },
  {
    studentName: "Phan Văn Khánh",
    studentClass: "12",
    studentClassCode: "T",
    studentMhs: "THCS_2132",
    studentMsv: "MSV_020",
    studentState: "Đang học",
    studentSemester: "2021-2025",
    studentGender: "Male",
    studentDantoc: "Kinh",
    studentNs: "Bình Định",
    studentCCCD: "034203005871",
    studentDob: "04/04/2003",
    studentEmail: "phanvankhanh@gmail.com",
    studentNumber: "0843210987",
    studentAddress: "Quy Nhơn, Bình Định",
    studentResident: "Bình Định",
  },
];

const combinedData = users.map((user) => {
  const student = studentInfor.find((info) => info.studentEmail === user.email);
  return {
    ...user,
    ...student,
  };
});

export const getAccount = (username: string) => {
  return combinedData.find((user) => user.username === username);
};

export const updatePassword = (username: string, newPassword: string) => {
  const user = getAccount(username);
  if (user) {
    user.password = newPassword;
  }
};
